export type WalletProvider = { id: string; name: string };
import { Address, Value } from "@emurgo/cardano-serialization-lib-asmjs";

export type WalletSnapshot = { walletId: string; walletName: string; networkId: number; networkMagic: number | null; signingAddress: string; signingAddressBech32?: string; balanceLovelace: string; rewardAddresses: string[]; utxoCount: number | null; origin: string; tabId?: number; observedAt: string };
export type SignatureReceipt = { signature: string; key: string; address: string; addressBech32?: string; payloadHex: string; signedAt: string; origin: string; walletId: string };

type Cip30Api = { getNetworkId(): Promise<number>; getBalance(): Promise<string>; getChangeAddress(): Promise<string>; getRewardAddresses(): Promise<string[]>; signData(address: string, payload: string): Promise<{ signature: string; key: string }>; cip142?: { getNetworkMagic(): Promise<number> } };
type Provider = { name?: string; supportedExtensions?: Array<{ cip: number }>; enable(options?: { extensions: Array<{ cip: number }> }): Promise<Cip30Api> };
type Read = Omit<WalletSnapshot, "walletId" | "walletName" | "tabId" | "observedAt">;
type RawRead = Omit<Read, "balanceLovelace" | "signingAddressBech32"> & { balanceCbor: string };
type WalletFailure = { message: string; info?: string; code?: string | number };
type WalletEnvelope<T> = { ok: true; data: T } | { ok: false; error: WalletFailure };
declare global { interface Window { cardano?: Record<string, Provider | undefined> } }

const label = (id: string, provider?: Provider) => provider?.name || id.replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
const hasChrome = () => typeof chrome !== "undefined" && Boolean(chrome.tabs && chrome.scripting);
const errorText = (error: unknown) => { const record = error && typeof error === "object" ? error as { message?: unknown; info?: unknown; code?: unknown } : {}; const message = String(record.info || record.message || error || "Unknown wallet error"); const code = record.code === undefined ? "" : ` (code ${String(record.code)})`; if (/^Wallet request (failed|was declined)|^Wallet access is unavailable/.test(message)) return message; if (/reject|denied|declined|cancel|refused/i.test(message)) return "Wallet request was declined. Review and approve it in your wallet to continue."; if (/cannot access|permission|chrome:\/\//i.test(message)) return "Wallet access is unavailable on this browser page. Open a regular http(s) website."; return `Wallet request failed: ${message}${code}`; };

// Self-contained because Chrome serializes this function into the page MAIN world.
async function injectedRead(walletId: string, expectedOrigin?: string): Promise<WalletEnvelope<RawRead>> {
  try {
    if (expectedOrigin && location.origin !== expectedOrigin) throw new Error("This wallet session belongs to a different site. Connect again on the current page.");
    const provider = (window as typeof window & { cardano?: Record<string, Provider | undefined> }).cardano?.[walletId];
    if (!provider?.enable) throw new Error("Wallet provider is unavailable on this page.");
    const api = provider.supportedExtensions?.some((extension) => extension.cip === 142) ? await provider.enable({ extensions: [{ cip: 142 }] }) : await provider.enable();
    const [networkId, signingAddress, balanceCbor, rewardAddresses] = await Promise.all([api.getNetworkId(), api.getChangeAddress(), api.getBalance(), api.getRewardAddresses()]);
    const networkMagic = api.cip142?.getNetworkMagic ? await api.cip142.getNetworkMagic() : null;
    return { ok: true, data: { networkId: Number(networkId), networkMagic: networkMagic === null ? null : Number(networkMagic), signingAddress: String(signingAddress), balanceCbor: String(balanceCbor), rewardAddresses: Array.isArray(rewardAddresses) ? rewardAddresses.map(String) : [], utxoCount: null, origin: location.origin } };
  } catch (error) { const record = error && typeof error === "object" ? error as { message?: unknown; info?: unknown; code?: unknown } : {}; return { ok: false, error: { message: String(record.message || record.info || error || "Wallet request failed"), info: record.info === undefined ? undefined : String(record.info), code: typeof record.code === "string" || typeof record.code === "number" ? record.code : undefined } }; }
}
async function injectedList(): Promise<WalletEnvelope<WalletProvider[]>> { try { const providers = (window as typeof window & { cardano?: Record<string, Provider | undefined> }).cardano || {}; return { ok: true, data: Object.entries(providers).filter(([, provider]) => Boolean(provider?.enable)).map(([id, provider]) => ({ id, name: provider?.name || id.replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) })) }; } catch (error) { const record = error && typeof error === "object" ? error as { message?: unknown; info?: unknown; code?: unknown } : {}; return { ok: false, error: { message: String(record.message || record.info || error || "Wallet request failed"), info: record.info === undefined ? undefined : String(record.info), code: typeof record.code === "string" || typeof record.code === "number" ? record.code : undefined } }; } }
async function injectedSign(walletId: string, expectedOrigin: string, expectedNetworkId: number, expectedNetworkMagic: number | null, expectedAddress: string, message: string): Promise<WalletEnvelope<Omit<SignatureReceipt, "signedAt" | "walletId" | "addressBech32">>> {
  try {
    if (location.origin !== expectedOrigin) throw new Error("This wallet session belongs to a different site. Connect again on the current page.");
    const provider = (window as typeof window & { cardano?: Record<string, Provider | undefined> }).cardano?.[walletId];
    if (!provider?.enable) throw new Error("Wallet provider is unavailable on this page.");
    const api = provider.supportedExtensions?.some((extension) => extension.cip === 142) ? await provider.enable({ extensions: [{ cip: 142 }] }) : await provider.enable();
    const [networkId, signingAddress] = await Promise.all([api.getNetworkId(), api.getChangeAddress()]);
    const networkMagic = api.cip142?.getNetworkMagic ? await api.cip142.getNetworkMagic() : null;
    if (Number(networkId) !== expectedNetworkId || Number(networkId) !== 0 || networkMagic !== expectedNetworkMagic || networkMagic !== 1 || signingAddress !== expectedAddress) throw new Error("Wallet account or network changed. Reconnect before signing.");
    const payloadHex = Array.from(new TextEncoder().encode(message), (byte) => byte.toString(16).padStart(2, "0")).join("");
    if (location.origin !== expectedOrigin) throw new Error("This wallet session belongs to a different site. Connect again on the current page.");
    const signed = await api.signData(signingAddress, payloadHex);
    return { ok: true, data: { signature: String(signed.signature), key: String(signed.key), address: String(signingAddress), payloadHex, origin: location.origin } };
  } catch (error) { const record = error && typeof error === "object" ? error as { message?: unknown; info?: unknown; code?: unknown } : {}; return { ok: false, error: { message: String(record.message || record.info || error || "Wallet request failed"), info: record.info === undefined ? undefined : String(record.info), code: typeof record.code === "string" || typeof record.code === "number" ? record.code : undefined } }; }
}
function hydrateRead(raw: RawRead): Read { const value = Value.from_hex(raw.balanceCbor); const address = Address.from_hex(raw.signingAddress); try { return { ...raw, balanceLovelace: value.coin().to_str(), signingAddressBech32: address.to_bech32() }; } finally { value.free(); address.free(); } }
function unwrap<T>(result: WalletEnvelope<T>): T { if (!result.ok) throw result.error; return result.data; }
async function activeTab(): Promise<number> { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (tab?.id === undefined) throw new Error("Open a regular website tab before connecting a wallet."); return tab.id; }
async function inTab<Args extends unknown[], T>(tabId: number, func: (...args: Args) => Promise<T>, args: Args): Promise<T> { try { const [result] = await chrome.scripting.executeScript({ target: { tabId }, world: "MAIN", func, args }); if (!result?.result) throw new Error("Wallet did not return data."); return result.result as T; } catch (error) { throw new Error(errorText(error)); } }

export async function discoverWallets(): Promise<WalletProvider[]> { try { return !hasChrome() ? unwrap(await injectedList()) : unwrap(await inTab(await activeTab(), injectedList, [])); } catch (error) { throw new Error(errorText(error)); } }
export async function connectWallet(walletId: string): Promise<WalletSnapshot> { const observedAt = new Date().toISOString(); try { if (!hasChrome()) { const read = hydrateRead(unwrap(await injectedRead(walletId))); return { ...read, walletId, walletName: label(walletId, window.cardano?.[walletId]), observedAt }; } const tabId = await activeTab(); const read = hydrateRead(unwrap(await inTab(tabId, injectedRead, [walletId]))); return { ...read, walletId, walletName: label(walletId), tabId, observedAt }; } catch (error) { throw new Error(errorText(error)); } }
export async function refreshWallet(snapshot: WalletSnapshot): Promise<WalletSnapshot> { try { let read: Read; if (hasChrome()) { if (snapshot.tabId === undefined) throw new Error("This wallet session is not bound to a browser tab. Connect again."); read = hydrateRead(unwrap(await inTab(snapshot.tabId, injectedRead, [snapshot.walletId, snapshot.origin]))); } else read = hydrateRead(unwrap(await injectedRead(snapshot.walletId, snapshot.origin))); return { ...snapshot, ...read, observedAt: new Date().toISOString() }; } catch (error) { throw new Error(errorText(error)); } }
export async function signMessage(snapshot: WalletSnapshot, message: string): Promise<SignatureReceipt> { try { if (!message.trim()) throw new Error("Enter a message before requesting a signature."); if (new TextEncoder().encode(message).length > 512) throw new Error("Message must be 512 UTF-8 bytes or fewer."); if (snapshot.networkId !== 0 || snapshot.networkMagic !== 1) throw new Error("Signing is limited to Cardano Preprod (network ID 0, magic 1)."); let signed: Omit<SignatureReceipt, "signedAt" | "walletId" | "addressBech32">; if (hasChrome()) { if (snapshot.tabId === undefined) throw new Error("This wallet session is not bound to a browser tab. Connect again."); signed = unwrap(await inTab(snapshot.tabId, injectedSign, [snapshot.walletId, snapshot.origin, snapshot.networkId, snapshot.networkMagic, snapshot.signingAddress, message])); } else signed = unwrap(await injectedSign(snapshot.walletId, snapshot.origin, snapshot.networkId, snapshot.networkMagic, snapshot.signingAddress, message)); if (!/^(?:[0-9a-f]{2})+$/i.test(signed.signature) || !/^(?:[0-9a-f]{2})+$/i.test(signed.key)) throw new Error("Wallet returned an invalid signature receipt."); let addressBech32: string | undefined; try { const address = Address.from_hex(signed.address); try { addressBech32 = address.to_bech32(); } finally { address.free(); } } catch { /* Raw address remains available if a wallet returns malformed data. */ } return { ...signed, addressBech32, walletId: snapshot.walletId, signedAt: new Date().toISOString() }; } catch (error) { throw new Error(errorText(error)); } }
