import Link from "next/link";
import { journey } from "@/lib/journey";

export default function TestingGuide() {
  return <main className="testing-guide"><Link href="/chat">← Back to chat</Link><h1>Full-flow test checklist</h1><p>This workspace connects to the deployed Eve QA agent. It exposes conversation, tool output, questions and approval requests. A chat response is not proof that an escrow, browser run or settlement happened.</p>
    <h2>Before the first message</h2><ul><li>Set <code>QA_AGENT_URL</code> and authentication in the chat project’s <code>.env</code>. Restart Next.js after changes.</li><li>For shared-token authentication, set the same <code>QA_AGENT_BEARER_TOKEN</code> in the agent deployment and redeploy the updated channel. A Vercel protection bypass alone does not authenticate to Eve.</li><li>Use “Recheck agent connection”. Both health and authenticated inspection must succeed.</li><li>Prepare the target URL/build, isolated funded test wallet, network/chain ID, allowlisted contracts and spender, token metadata, fixtures, transaction limits and service budget.</li><li>Wallet secrets belong in the runner environment, never in this conversation.</li></ul>
    <h2>Exercise the journey</h2><table><thead><tr><th>Step</th><th>Required proof</th></tr></thead><tbody>{journey.map((step, index) => <tr key={step.title}><td>{index + 1}. {step.title}</td><td>{step.detail}</td></tr>)}</tbody></table>
    <h2>Current integration boundaries</h2><ul><li><strong>Interview and plan:</strong> available through Eve tools. Inspect source labels, essential question IDs, case IDs, expectations, quote, version, evidence and recovery limits.</li><li><strong>Approval and escrow:</strong> require a trusted host to persist the exact approved plan and buyer identity. Chat has no bridge to the separate paid-service API and never creates a payment.</li><li><strong>Runner:</strong> Qwap/QMS is the implemented browser journey. Generic wallet journeys and NuFi/Minswap are not complete runners. The deployed runtime needs browser support and fixture credentials; local runner success does not prove deployment readiness.</li><li><strong>Delivery:</strong> open actual report/evidence URLs returned by the service. Local host paths are not downloadable remote artifacts. Required missing proof must prevent PASS.</li><li><strong>Settlement:</strong> inspect Masumi escrow state and human-review deadlines in the paid service. x402 direct payment has different terms and no automatic refunds; it is not equivalent to escrow.</li></ul>
    <h2>Checks to run</h2><ol><li>Send a request with missing prerequisites; confirm the agent asks essential questions without executing.</li><li>Answer, request a plan, and revise an expectation. Confirm version/snapshot changes and exact quote review.</li><li>Test a tool approval: inspect the action, reject it, and confirm the tool does not execute. Questions and tool approvals appear inline only when emitted by the backend.</li><li>Refresh during a turn; the same session should replay and continue. Press Stop and wait for cancellation before starting a new conversation.</li><li>Through the trusted paid host, persist the approved plan, verify funding, run within its limits, and inspect checkpoints and artifacts.</li><li>Check PASS, FLAKY, FAIL, BLOCKED, INCONCLUSIVE, RUNNER_ERROR and NOT_RUN against evidence. Review service completeness and settlement separately.</li><li>Export chat for debugging. It contains conversation/tool data, not a sealed evidence bundle.</li></ol>
  </main>;
}
